/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequest"];
                };
            };
            responses: {
                /** @description Project created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id|slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id or slug of the project */
                "id|slug": components["parameters"]["ProjectIdentifier"];
            };
            cookie?: never;
        };
        /** Find project by id or slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or slug of the project */
                    "id|slug": components["parameters"]["ProjectIdentifier"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id|slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id or slug of the project */
                "id|slug": components["parameters"]["ProjectIdentifier"];
            };
            cookie?: never;
        };
        /** List project members */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or slug of the project */
                    "id|slug": components["parameters"]["ProjectIdentifier"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectMember"][];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Project: {
            /** @description Unique identifier of the project */
            id: string;
            /** @description Name of the project */
            name: string;
            /** @description URL-friendly identifier */
            slug: string;
            /** @description Short summary of the project */
            summary?: string | null;
            /** @description Detailed description of the project */
            description?: string | null;
            /**
             * Format: uri
             * @description URL to the project's icon
             */
            iconUrl?: string | null;
            /**
             * Format: int64
             * @description Number of downloads
             */
            downloads: number;
            type: components["schemas"]["ProjectType"];
            status: components["schemas"]["ProjectStatus"];
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updatedAt: string;
            /** @description Identifier of the user */
            userId?: string;
        };
        /** @enum {string} */
        ProjectType: "mod";
        /** @enum {string} */
        ProjectStatus: "draft" | "rejected" | "approved" | "banned";
        ProjectMember: {
            username: string;
            userId: string;
            image?: string;
            role: components["schemas"]["ProjectMemberRole"];
        };
        /** @enum {string} */
        ProjectMemberRole: "owner" | "admin" | "developer" | "maintainer" | "member";
        CreateProjectRequest: {
            type: components["schemas"]["ProjectType"];
            /** @description Name of the project */
            name: string;
            /** @description Slug of the project */
            slug: string;
            /** @description Summary of the project */
            summary?: string;
        };
        ProblemDetails: {
            /** @description A short, human-readable summary of the problem */
            title: string;
            /**
             * Format: int32
             * @description The HTTP status code
             */
            status: number;
            /** @description A human-readable explanation specific to this occurrence of the problem */
            detail: string;
            /** @description List of validation errors (if applicable) */
            errors?: components["schemas"]["ValidationError"][];
        };
        ValidationError: {
            /** @description Name of the field where the error occurred */
            field?: string;
            /** @description Machine-readable error code */
            code?: string;
            /** @description Human-readable error message */
            message?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description The id or slug of the project */
        ProjectIdentifier: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
