/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search projects */
        get: {
            parameters: {
                query?: {
                    query?: string;
                    type?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectSearch"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Create a new project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequest"];
                };
            };
            responses: {
                /** @description Project created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id|slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id or slug of the project */
                "id|slug": components["parameters"]["ProjectIdentifier"];
            };
            cookie?: never;
        };
        /** Find project by id or slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or slug of the project */
                    "id|slug": components["parameters"]["ProjectIdentifier"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete project */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or slug of the project */
                    "id|slug": components["parameters"]["ProjectIdentifier"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update project */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or slug of the project */
                    "id|slug": components["parameters"]["ProjectIdentifier"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProjectRequest"];
                };
            };
            responses: {
                /** @description successful operation */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/projects/{id|slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id or slug of the project */
                "id|slug": components["parameters"]["ProjectIdentifier"];
            };
            cookie?: never;
        };
        /** List project members */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or slug of the project */
                    "id|slug": components["parameters"]["ProjectIdentifier"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectMember"][];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loader-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List of loader versions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoaderVersion"][];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id|slug}/releases/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id or slug of the project */
                "id|slug": components["parameters"]["ProjectIdentifier"];
            };
            cookie?: never;
        };
        /** Generate a presigned put url */
        get: {
            parameters: {
                query: {
                    fileSize: number;
                };
                header?: never;
                path: {
                    /** @description The id or slug of the project */
                    "id|slug": components["parameters"]["ProjectIdentifier"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorised */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id|slug}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id or slug of the project */
                "id|slug": components["parameters"]["ProjectIdentifier"];
            };
            cookie?: never;
        };
        /** Get project releases */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or slug of the project */
                    "id|slug": components["parameters"]["ProjectIdentifier"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectRelease"][];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Create project release */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The id or slug of the project */
                    "id|slug": components["parameters"]["ProjectIdentifier"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectReleaseRequest"];
                };
            };
            responses: {
                /** @description Project release created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectRelease"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Project: {
            /** @description Unique identifier of the project */
            id: string;
            /** @description Name of the project */
            name: string;
            /** @description URL-friendly identifier */
            slug: string;
            /** @description Short summary of the project */
            summary?: string | null;
            /** @description Detailed description of the project */
            description?: string | null;
            /**
             * Format: uri
             * @description URL to the project's icon
             */
            iconUrl?: string | null;
            /**
             * Format: int64
             * @description Number of downloads
             */
            downloads: number;
            type: components["schemas"]["ProjectType"];
            status: components["schemas"]["ProjectStatus"];
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updatedAt: string;
            /** @description Identifier of the user */
            userId?: string;
        };
        /** @enum {string} */
        ProjectType: "mod";
        /** @enum {string} */
        ProjectStatus: "draft" | "rejected" | "approved" | "banned";
        ProjectMember: {
            username: string;
            userId: string;
            image?: string;
            role: components["schemas"]["ProjectMemberRole"];
        };
        /** @enum {string} */
        ProjectMemberRole: "owner" | "admin" | "developer" | "maintainer" | "member";
        ProjectSearch: {
            data: components["schemas"]["Project"][];
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            totalHits: number;
        };
        /** @enum {string} */
        LoaderVersionBuildType: "stable" | "preview" | "legacy";
        LoaderVersion: {
            id: string;
            gameVersion: string;
            versionLabel: string;
            buildType: components["schemas"]["LoaderVersionBuildType"];
            /** Format: date-time */
            releasedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectRelease: {
            /** @description Version id */
            id: string;
            /** @description Project id */
            projectId: string;
            /** @description Version name */
            name: string;
            /** @description Version changelog */
            changelog?: string;
            versionNumber: string;
            loaderVersion: components["schemas"]["LoaderVersion"];
            /** Format: int64 */
            downloads: number;
            fileUrl: string;
            /** Format: int64 */
            fileSize: number;
            fileHash: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            publishedAt?: string;
            dependencies: components["schemas"]["ProjectReleaseDependency"][];
        };
        ProjectReleaseDependency: {
            /** @description id */
            id: string;
            releaseId: string;
            dependencyProjectId: string;
            dependencyType: components["schemas"]["ProjectReleaseDependencyType"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        ProjectReleaseDependencyType: "required" | "optional";
        CreateProjectReleaseDependencyRequest: {
            type: components["schemas"]["ProjectReleaseDependencyType"];
            projectId: string;
            minVersionNumber?: string;
        };
        CreateProjectReleaseRequest: {
            name: string;
            versionNumber: string;
            loaderVersionId: string;
            fileUrl: string;
            dependencies?: components["schemas"]["CreateProjectReleaseDependencyRequest"][];
        };
        CreateProjectRequest: {
            type: components["schemas"]["ProjectType"];
            /** @description Name of the project */
            name: string;
            /** @description Slug of the project */
            slug: string;
            /** @description Summary of the project */
            summary?: string;
        };
        UpdateProjectRequest: {
            /** @description Name of the project */
            name?: string;
            /** @description Slug of the project */
            slug?: string;
            /** @description Summary of the project */
            summary?: string;
            /** @description Description of the project */
            description?: string;
            /** @description Icon url of the project */
            iconUrl?: string;
        };
        ProblemDetails: {
            /** @description A short, human-readable summary of the problem */
            title: string;
            /**
             * Format: int32
             * @description The HTTP status code
             */
            status: number;
            /** @description A human-readable explanation specific to this occurrence of the problem */
            detail: string;
            /** @description List of validation errors (if applicable) */
            errors?: components["schemas"]["ValidationError"][];
        };
        ValidationError: {
            /** @description Name of the field where the error occurred */
            field?: string;
            /** @description Machine-readable error code */
            code?: string;
            /** @description Human-readable error message */
            message?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description The id or slug of the project */
        ProjectIdentifier: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
